#import "../../theorem.typ": theorem, claim, proof, definition, remark, note, theorem_rules
#definition("フェルミオン", [
  $cal(M) := {-M, dots, -2, -1, 1, 2, dots, M}$ とする。

  $mu in cal(M)$について、$psi_mu, psi_mu^dagger in "Mat"(2, CC)^(times.o M)$を、

  $
    mat(
      psi_mu^dagger,
      psi_mu
    )
    :&=
    (
      hat(Z)_mu^((minus)),
      hat(Y)_mu
    )
    dot.c
    P_mu
    \
    &=
    (
      hat(Z)_mu^((minus)),
      hat(Y)_mu
    )
    dot.c
    mat(
      plus
      sqrt(
        -1
      )
      sqrt(
        gamma_2(theta_(mu))
        gamma_2(-theta_(mu))
      )
      ,
      minus
      sqrt(
        -1
      )
      sqrt(
        gamma_2(theta_(mu))
        gamma_2(-theta_(mu))
      );
      gamma_2(-theta_(mu))
      ,
      gamma_2(-theta_(mu))
    )
    \
    &=
    (
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      hat(Z)_mu^((minus))
      +
      (
        gamma_2(-theta_(mu))
      )
      hat(Y)_mu
      ,
      (
        minus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      hat(Z)_mu^((minus))
      +
      (
        gamma_2(-theta_(mu))
      )
      hat(Y)_mu
    )
    \
    &=
    (
      hat(Z)_mu^((minus))
      +
      (
        gamma_2(-theta_(mu))
      )
      /
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      hat(Y)_mu
      ,
      hat(Z)_mu^((minus))
      +
      (
        gamma_2(-theta_(mu))
      )
      /
      (
        minus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      hat(Y)_mu
    )
    \
    &=
    (
      hat(Z)_mu^((minus))
      minus
      sqrt(
        -1
      )
      (
        gamma_2(-theta_(mu))
      )
      /
      (
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      hat(Y)_mu
      ,
      hat(Z)_mu^((minus))
      +
      sqrt(
        -1
      )
      (
        gamma_2(-theta_(mu))
      )
      /
      (
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      hat(Y)_mu
    )
  $

  と定める

  #note[
    #ref(<equation_of_a_theta_mu>) より、上記のフェルミオンの定義は
    $
      psi_mu^dagger
      :=
      hat(Y)_mu
      +
      sqrt(-1)
      a(theta_mu)
      hat(Z)_mu^((minus))
      \
      psi_mu
      :=
      hat(Y)_mu
      -
      sqrt(-1)
      a(theta_mu)
      hat(Z)_mu^((minus))
    $

    のようにも書ける。
    
    これは、ホロノミック量子場 付録B 式(B.11)(B.12) の定義とは
    - 定数倍を除いて一致する
    - $a(theta_mu)$が逆数になっている
    という違いがある。
  ]
])<def_fermi>
