#import "../../theorem.typ": theorem, claim, proof, definition, remark, note, theorem_rules
#claim([$V$と$psi$の交換関係(B.13)])[
  $cal(M) := {-M, dots, -2, -1, 1, 2, dots, M}$ とする。

  $mu in cal(M)$について、

  $
    T_((V))mat(psi_mu^dagger)
    &=
    (
      (
        gamma_1(theta_(mu))
      )
      plus
      sqrt(
        -
        (
          gamma_2(theta_(mu))
        )
        (
          gamma_2(-theta_(mu))
        )
      )
    )
    psi_mu^dagger
    \
    T_((V))(psi_mu)
    &=
    (
      (
        gamma_1(theta_(mu))
      )
      minus
      sqrt(
        -
        (
          gamma_2(theta_(mu))
        )
        (
          gamma_2(-theta_(mu))
        )
      )
    )
    psi_mu
  $

  #note[
    $
      (
        hat(Z)_mu^((minus)),
        hat(Y)_mu
      )
      dot.op
      A((2 pi mu) / M)
      &=
      mat(
        (
          c_1 c_2^*
          -
          s_1 s_2^* cos ((2 pi mu) / M)
        )
        hat(Z)_mu^((minus))
        +
        (
          - sqrt(-1) exp(-sqrt(-1) (2 pi mu) / M) s_2^* (c_1 cos ((2 pi mu) / M) + sqrt(-1) sin ((2 pi mu) / M) - s_1 c_2)
        )
        hat(Y)_mu,
        (
          sqrt(-1) exp(sqrt(-1) (2 pi mu) / M) s_2^* (c_1 cos ((2 pi mu) / M) - sqrt(-1) sin ((2 pi mu) / M) - s_1 c_2)
        )
        hat(Z)_mu^((minus))
        +
        (
          c_1 c_2^*
          -
          s_1 s_2^* cos ((2 pi mu) / M)
        )
        hat(Y)_mu
      )
    $
  ]

  #proof[
    $
      mat(
        T_((V))(psi_mu^dagger),
        T_((V))(psi_mu)
      )
      &=
      T_((V))
      mat(
        psi_mu^dagger,
        psi_mu
      )
      \
      &=
      T_((V))
      (
        (
          hat(Z)_mu^((minus)),
          hat(Y)_mu
        )
        dot.c
        P_mu
      )
      quad
      (because #ref(<mat_conj>)"より、" T_((V))"は線形写像")
      \
      &=
      T_((V))
      (
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        hat(Z)_mu^((minus))
        +
        (
          gamma_2(-theta_(mu))
        )
        hat(Y)_mu
        ,
        (
          minus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        hat(Z)_mu^((minus))
        +
        (
          gamma_2(-theta_(mu))
        )
        hat(Y)_mu
      )
      \
      &=
      (
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        T_((V))
        (
          hat(Z)_mu^((minus))
        )
        +
        (
          gamma_2(-theta_(mu))
        )
        T_((V))
        (
          hat(Y)_mu
        )
        ,
        (
          minus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        T_((V))
        (
          hat(Z)_mu^((minus))
        )
        +
        (
          gamma_2(-theta_(mu))
        )
        T_((V))
        (
          hat(Y)_mu
        )
      )
      \
      &=
      mat(
        T_((V))
        (
          hat(Z)_mu^((minus))
        ),
        T_((V))
        (
          hat(Y)_mu
        )
      )
      mat(
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        ,
        (
          minus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        );
        (
          gamma_2(-theta_(mu))
        ),
        (
          gamma_2(-theta_(mu))
        )
      )
      \
      &=
      mat(
        hat(Z)_mu^((minus))
        ,
        hat(Y)_mu
      )
      A(theta_(mu))
      P_mu
      \
      &=
      mat(
        hat(Z)_mu^((minus))
        ,
        hat(Y)_mu
      )
      (
        P_mu
        D_mu
        P_mu
        ^
        (-1)
      )
      P_mu
      \
      &=
      mat(
        hat(Z)_mu^((minus))
        ,
        hat(Y)_mu
      )
      P_mu
      D_mu
      \
      &=
      mat(
        psi_mu^dagger,
        psi_mu
      )
      D_mu
      \
      &=
      mat(
        psi_mu^dagger,
        psi_mu
      )
      mat(
        (
          gamma_1(theta_(mu))
        )
        plus
        sqrt(
          -
          (
            gamma_2(theta_(mu))
          )
          (
            gamma_2(-theta_(mu))
          )
        ),
        0
        ;
        0,
        (
          gamma_1(theta_(mu))
        )
        minus
        sqrt(
          -
          (
            gamma_2(theta_(mu))
          )
          (
            gamma_2(-theta_(mu))
          )
        )
      )
      \
      &=
      mat(
        (
          (
            gamma_1(theta_(mu))
          )
          plus
          sqrt(
            -
            (
              gamma_2(theta_(mu))
            )
            (
              gamma_2(-theta_(mu))
            )
          )
        )
        psi_mu^dagger,
        (
          (
            gamma_1(theta_(mu))
          )
          minus
          sqrt(
            -
            (
              gamma_2(theta_(mu))
            )
            (
              gamma_2(-theta_(mu))
            )
          )
        )
        psi_mu
      )
      \
      qed
    $
  ]
]
