#import "../../theorem.typ": theorem, claim, proof, definition, remark, note, theorem_rules
#claim([$psi$の反交換関係])[
  $cal(M) := {-M, dots, -2, -1, 1, 2, dots, M}$ とする。

  $mu, nu in cal(M)$について、

  $
    [psi_mu^dagger, psi_nu^dagger]_(+) &= 0
    \
    [psi_mu^dagger, psi_nu]_(+) &= delta_(mu equiv nu (mod M))
    \
    [psi_mu, psi_nu]_(+) &= 0
  $

  #proof[
    $a) [psi_mu^dagger, psi_nu^dagger]_(+)$について、

    $
      [psi_mu^dagger, psi_nu^dagger]_(+)
      &=
      [
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        hat(Z)_mu^((minus))
        +
        (
          gamma_2(-theta_(mu))
        )
        hat(Y)_mu
        ,
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(nu))
            gamma_2(-theta_(nu))
          )
        )
        hat(Z)_nu^((minus))
        +
        (
          gamma_2(-theta_(nu))
        )
        hat(Y)_nu
      ]_(+)
      \
      &=
      [
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        hat(Z)_mu^((minus))
        ,
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(nu))
            gamma_2(-theta_(nu))
          )
        )
        hat(Z)_nu^((minus))
        +
        (
          gamma_2(-theta_(nu))
        )
        hat(Y)_nu
      ]_(+)
      +
      [
        (
          gamma_2(-theta_(mu))
        )
        hat(Y)_mu
        ,
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(nu))
            gamma_2(-theta_(nu))
          )
        )
        hat(Z)_nu^((minus))
        +
        (
          gamma_2(-theta_(nu))
        )
        hat(Y)_nu
      ]_(+)
      \
      &=
      [
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        hat(Z)_mu^((minus))
        ,
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(nu))
            gamma_2(-theta_(nu))
          )
        )
        hat(Z)_nu^((minus))
      ]_(+)
      +
      [
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        hat(Z)_mu^((minus))
        ,
        (
          gamma_2(-theta_(nu))
        )
        hat(Y)_nu
      ]_(+)
      +
      [
        (
          gamma_2(-theta_(mu))
        )
        hat(Y)_mu
        ,
        (
          plus
          sqrt(
            -1
          )
          sqrt(
            gamma_2(theta_(nu))
            gamma_2(-theta_(nu))
          )
        )
        hat(Z)_nu^((minus))
      ]_(+)
      +
      [
        (
          gamma_2(-theta_(mu))
        )
        hat(Y)_mu
        ,
        (
          gamma_2(-theta_(nu))
        )
        hat(Y)_nu
      ]_(+)
      ]_(+)
      \
      &=
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(nu))
          gamma_2(-theta_(nu))
        )
      )
      [
        hat(Z)_mu^((minus))
        ,
        hat(Z)_nu^((minus))
      ]_(+)
      +
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      (
        gamma_2(-theta_(nu))
      )
      [
        hat(Z)_mu^((minus))
        ,
        hat(Y)_nu
      ]_(+)
      +
      (
        gamma_2(-theta_(mu))
      )
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(nu))
          gamma_2(-theta_(nu))
        )
      )
      [
        hat(Y)_mu
        ,
        hat(Z)_nu^((minus))
      ]_(+)
      +
      (
        gamma_2(-theta_(mu))
      )
      (
        gamma_2(-theta_(nu))
      )
      [
        hat(Y)_mu
        ,
        hat(Y)_nu
      ]_(+)
      \
      &=
      minus
      (
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      (
        sqrt(
          gamma_2(theta_(nu))
          gamma_2(-theta_(nu))
        )
      )
      dot.op
      (
        2M delta^M_(mu + nu, 0) I_((CC^2)^(times.o M))
      )
      +
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      (
        gamma_2(-theta_(nu))
      )
      dot.op
      0
      +
      (
        gamma_2(-theta_(mu))
      )
      (
        plus
        sqrt(
          -1
        )
        sqrt(
          gamma_2(theta_(nu))
          gamma_2(-theta_(nu))
        )
      )
      dot.op
      0
      +
      (
        gamma_2(-theta_(mu))
      )
      (
        gamma_2(-theta_(nu))
      )
      dot.op
      (
        2M delta^M_(mu + nu, 0) I_((CC^2)^(times.o M))
      )
      \
      &=
      minus
      (
        sqrt(
          gamma_2(theta_(mu))
          gamma_2(-theta_(mu))
        )
      )
      (
        sqrt(
          gamma_2(theta_(nu))
          gamma_2(-theta_(nu))
        )
      )
      dot.op
      (
        2M delta^M_(mu + nu, 0) I_((CC^2)^(times.o M))
      )
      +
      (
        gamma_2(-theta_(mu))
      )
      (
        gamma_2(-theta_(nu))
      )
      dot.op
      (
        2M delta^M_(mu + nu, 0) I_((CC^2)^(times.o M))
      )
      \
      &=
      (
        minus
        (
          sqrt(
            gamma_2(theta_(mu))
            gamma_2(-theta_(mu))
          )
        )
        (
          sqrt(
            gamma_2(theta_(nu))
            gamma_2(-theta_(nu))
          )
        )
        +
        (
          gamma_2(-theta_(mu))
        )
        (
          gamma_2(-theta_(nu))
        )
      )
      dot.op
      (
        2M delta^M_(mu + nu, 0) I_((CC^2)^(times.o M))
      )
      \
      &=
      (
        minus
        abs(
          gamma_2(theta_(mu))
        )
        abs(
          gamma_2(theta_(nu))
        )
        +
        (
          overline(
            gamma_2(theta_(mu))
          )
        )
        (
          overline(
            gamma_2(theta_(nu))
          )
        )
      )
      dot.op
      (
        2M delta^M_(mu + nu, 0) I_((CC^2)^(times.o M))
      )
    $

    (次回 20250614) WIP

    #note[
      $
        mat(
          psi_mu^dagger,
          psi_mu
        )
        :=
        (
          (
            plus
            sqrt(
              -1
            )
            sqrt(
              gamma_2(theta_(mu))
              gamma_2(-theta_(mu))
            )
          )
          hat(Z)_mu^((minus))
          +
          (
            gamma_2(-theta_(mu))
          )
          hat(Y)_mu
          ,
          (
            minus
            sqrt(
              -1
            )
            sqrt(
              gamma_2(theta_(mu))
              gamma_2(-theta_(mu))
            )
          )
          hat(Z)_mu^((minus))
          +
          (
            gamma_2(-theta_(mu))
          )
          hat(Y)_mu
        )
      $

      $
        [hat(Z)_mu^((plus.minus)), hat(Z)_nu^((plus.minus))]_(+) = 2M delta^M_(mu + nu, 0) I
        quad ("複合同順")
        \
        [hat(Z)_mu^((plus.minus)), hat(Z)_nu^((minus.plus))]_(+) = underbrace(
            2M delta^M_(mu + nu, 0)
            I_((CC^2)^(times.o M))
            ,
            [hat(Z)_mu^((plus.minus)), hat(Z)_nu^((plus.minus))]_(+)
            )
            +
            (
              -2
              exp(
                -
                sqrt(-1)
                (2 pi) / M
                (
                  mu
                  +
                  nu
                )
              )
              dot.op
              2I_((CC^2)^(times.o M))
            )
        quad ("複合同順")
        \
        [hat(Z)_mu^((plus.minus)), hat(Y)_nu]_(+) = 0
        \
        [hat(Y)_mu, hat(Y)_nu]_(+) = 2M delta^M_(mu + nu, 0) I
      $

    ]
  ]
]
